feat:Добавить контроллеры для Item и User
Omorlan/java-shareit pull request #1
Opened 2024-08-10 22:24 UTC by Omorlan

2024-08-11 19:12 UTC, afomkina requested changes

2024-08-11 19:12 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    Long id;
Не хватает модификатора доступа

2024-08-11 19:12 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryInMemory.java
> +    private final Map<Long, Item> itemMap;
Лучше здесь явно инициализировать мапу
```suggestion
    private final Map<Long, Item> itemMapc = new HashMap<>();
```

2024-08-11 19:12 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public List<ItemDto> searchItemDto(@RequestHeader(USER_HEADER) Long userId,
Параметр `userId` не используется

2024-08-11 19:12 UTC, afomkina commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    long id;
У полей класса не хватает модфикаторов доступа

2024-08-11 19:12 UTC, afomkina commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryInMemory.java
> +    private final Map<Long, User> userMap;
Лучше здесь явно проинициализировать мапу

2024-08-11 19:12 UTC, afomkina commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    private void validateEmail(UserDto userDto) {
_Дополнительные оптимизации_
Чтобы проверка почты проходила за [O(1)](https://skillbox.ru/media/code/big-o-notation-chto-eto-takoe-i-kak-eye-poschitat/), нужно завести Set, куда при добавлении нового пользователя мы будем класть его email. Соответственно, перед тем как добавить пользователя, нужно будет посмотреть, есть ли уже в сете подобный email, если есть - то пользователь с таким email уже существует.

Так как поиск и вставка в сете работают в среднем за O(1), то наш алгоритм поиска одинаковых email тоже будет работать в среднем за O(1), а это гораздо быстрее, чем пройтись по всем элементам списка O(n)

2024-08-12 08:08 UTC, Omorlan commented
![image](https://github.com/user-attachments/assets/187d8075-0453-4cb9-b983-270789bc4e10)
проверка крашится тут но, у меня все стратует 
![image](https://github.com/user-attachments/assets/5c25c5ab-303a-4af6-9e5c-a07cd3ffbe45)
и работает
![image](https://github.com/user-attachments/assets/38f95df9-aa0d-49e3-a9bd-17ebdd1583a2)

2024-08-13 01:30 UTC, afomkina commented
Нужно обратиться за помощью к наставнику, и починить билд. По правилам я не могу смотреть работу, если она не прошла проверки

2024-08-14 13:33 UTC, afomkina approved these changes

2024-08-26 12:33 UTC, merged