feat: реализовать функционал 15 ТЗ
Omorlan/java-shareit pull request #2
Opened 2024-08-29 13:52 UTC by Omorlan

2024-08-30 14:10 UTC, afomkina requested changes
Привет! Работа получилась отличная, оставила немного комментариев для саморазвития

2024-08-30 14:10 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    private static final String USER_HEADER = "X-Sharer-User-Id";
Эта константа используется и в других контроллерах, лучше вынести ее в одельный утильный класс и сделать общедоступной

2024-08-30 14:10 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return switch (state) {
_Задание со "*"_
Данный блок кода можно оптимизировать с помощью паттерна проектирования 
[Цепочка обязанностей](https://refactoring.guru/ru/design-patterns/chain-of-responsibility) (сайт может не открываться без vpn).
Предлагаю изучить этот паттерн и попробовать реализовать его.

В коммерческой разработке очень часто используются паттерны проектирования, так как код становится более чистым и структурированным. А еще его становится проще поддерживать и масштабировать. 

А еще их часто спрашивают на собеседованиях 😉

2024-08-30 14:10 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return switch (state) {
И здесь тоже подойдет цепочка обязанностей

2024-08-30 14:10 UTC, afomkina commented on src/main/resources/schema.sql
_Опционально_
Предлагаю попробовать добавить индексы, чтобы ускорить поиск:
[статья](https://tproger.ru/articles/indeksy-v-postgresql/)
[видео](https://www.youtube.com/watch?v=DyqtBiDrz3g)

2024-09-01 21:21 UTC, Omorlan commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    private static final String USER_HEADER = "X-Sharer-User-Id";
вынес

2024-09-01 21:22 UTC, Omorlan commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return switch (state) {
цепочку вроде выстроил как мог, на сколько времени хватило

2024-09-01 21:23 UTC, Omorlan commented on src/main/resources/schema.sql
Про индексы знаю, если руки дойдут то в следующем тз, дедлайны горят)

2024-09-02 12:08 UTC, afomkina approved these changes
Получилась отличная цепочка обязанностей, молодец 👍

2024-09-03 13:51 UTC, merged